// Generated by scripts/import-feedsport-ingredients.mjs. Do not edit by hand.
import manifest from "./manifest.json";
import nutrients from "./nutrients.json";
import ingredients01 from "./ingredients/ingredients-01.json";
import ingredients02 from "./ingredients/ingredients-02.json";
import ingredients03 from "./ingredients/ingredients-03.json";
import ingredients04 from "./ingredients/ingredients-04.json";
import ingredients05 from "./ingredients/ingredients-05.json";
import ingredients06 from "./ingredients/ingredients-06.json";
import ingredients07 from "./ingredients/ingredients-07.json";
import ingredients08 from "./ingredients/ingredients-08.json";
import ingredients09 from "./ingredients/ingredients-09.json";
import ingredients10 from "./ingredients/ingredients-10.json";
import ingredients11 from "./ingredients/ingredients-11.json";
import ingredients12 from "./ingredients/ingredients-12.json";
import ingredients13 from "./ingredients/ingredients-13.json";
import ingredients14 from "./ingredients/ingredients-14.json";
import ingredients15 from "./ingredients/ingredients-15.json";
import ingredients16 from "./ingredients/ingredients-16.json";
import ingredients17 from "./ingredients/ingredients-17.json";

export const feedSportManifestJson = manifest;
export const feedSportNutrientsJson = nutrients;
export const feedSportIngredientRowsJson = [
  ...ingredients01,
  ...ingredients02,
  ...ingredients03,
  ...ingredients04,
  ...ingredients05,
  ...ingredients06,
  ...ingredients07,
  ...ingredients08,
  ...ingredients09,
  ...ingredients10,
  ...ingredients11,
  ...ingredients12,
  ...ingredients13,
  ...ingredients14,
  ...ingredients15,
  ...ingredients16,
  ...ingredients17,
];
