import type { Workbook } from "exceljs";

import type { PlanSimulationResult, ProductionMortalityStage } from "../simulation-result";
import { applyBase, COLORS, NUMBER_FORMAT, PORTRAIT_PAGE, ruleRow, solidFill, styleTableHeader, styleTitle } from "./sheet";

const LABELS: Record<ProductionMortalityStage, string> = { piglet: "Pre-weaning", weaner: "Weaner / nursery", grower: "Grower", finisher: "Finisher" };

export type MortalityReportRow = { stage: ProductionMortalityStage; label: string; entered: number; deaths: number; observedRatePct: number; configuredRatePct: number; variancePctPoints: number };
export type MortalityReport = { projectName: string; rows: MortalityReportRow[]; totalDeaths: number };

export function mortalityReport(result: PlanSimulationResult): MortalityReport {
  const rows = result.mortality.stages.map((row) => ({ ...row, label: LABELS[row.stage], variancePctPoints: row.observedRatePct - row.configuredRatePct }));
  return { projectName: result.config.project.name, rows, totalDeaths: result.mortality.totalDeaths };
}

export function addMortalitySheet(workbook: Workbook, report: MortalityReport, generatedAt: Date): void {
  const sheet = workbook.addWorksheet("Mortality by stage");
  sheet.pageSetup = PORTRAIT_PAGE;
  sheet.properties.defaultRowHeight = 18;
  sheet.columns = [{ key: "stage", width: 24 }, { key: "entered", width: 14 }, { key: "deaths", width: 12 }, { key: "observed", width: 16 }, { key: "configured", width: 16 }, { key: "variance", width: 14 }];
  styleTitle(sheet, report.projectName + " — mortality by stage", "Observed production losses from the simulated run, compared with the mortality assumptions entered in the plan.", "F");
  const header = sheet.getRow(6);
  header.values = ["Stage", "Entered stage", "Deaths", "Observed", "Configured", "Variance"];
  styleTableHeader(header);
  let rowNumber = 7;
  for (const row of report.rows) {
    const excelRow = sheet.getRow(rowNumber);
    excelRow.values = [row.label, row.entered, row.deaths, row.observedRatePct / 100, row.configuredRatePct / 100, row.variancePctPoints / 100];
    excelRow.getCell(2).numFmt = NUMBER_FORMAT;
    excelRow.getCell(3).numFmt = NUMBER_FORMAT;
    excelRow.getCell(4).numFmt = "0.0%";
    excelRow.getCell(5).numFmt = "0.0%";
    excelRow.getCell(6).numFmt = "+0.0%;-0.0%;-";
    if (row.variancePctPoints > 0.05) { excelRow.getCell(6).fill = solidFill(COLORS.paleRed); excelRow.getCell(6).font = { color: { argb: COLORS.red } }; }
    else if (row.variancePctPoints < -0.05) { excelRow.getCell(6).fill = solidFill(COLORS.paleGreen); excelRow.getCell(6).font = { color: { argb: COLORS.green } }; }
    ruleRow(sheet, rowNumber, 6);
    rowNumber += 1;
  }
  rowNumber += 1;
  sheet.mergeCells(rowNumber, 1, rowNumber, 6);
  const note = sheet.getCell(rowNumber, 1);
  note.value = "Observed mortality = deaths in the stage ÷ animals entering that stage during the simulated period, including opening stock already in that stage. Animals entering near the end of the planning horizon may still be exposed after the horizon, so observed and configured rates are not expected to match exactly.";
  note.alignment = { wrapText: true, vertical: "top" };
  note.font = { italic: true, color: { argb: COLORS.muted } };
  sheet.getRow(rowNumber).height = 48;
  rowNumber += 2;
  sheet.mergeCells(rowNumber, 1, rowNumber, 6);
  sheet.getCell(rowNumber, 1).value = "Generated by PigFlow · " + generatedAt.toISOString();
  sheet.getCell(rowNumber, 1).font = { size: 9, color: { argb: COLORS.muted } };
  sheet.autoFilter = { from: "A6", to: "F6" };
  sheet.views = [{ state: "frozen", ySplit: 6, showGridLines: false }];
  applyBase(sheet);
}
